# fly.toml app configuration file generated for hex-mcp on 2025-02-18T22:40:55+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'hex-mcp'
primary_region = 'arn'
kill_signal = 'SIGTERM'

[build]

[env]
  PHX_HOST = 'hex-mcp.9elements.com'
  PORT = '8080'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 1
  processes = ['app']

  [http_service.concurrency]
    type = 'connections'
    hard_limit = 1000
    soft_limit = 1000

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
