# fly.toml app configuration file generated for dep-mcp on 2025-02-20T11:56:06+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'dep-mcp'
primary_region = 'arn'
kill_signal = 'SIGTERM'

[build]

[env]
  PHX_HOST = 'dep-mcp.fly.dev'
  PORT = '8080'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 1
  processes = ['app']

  [http_service.concurrency]
    type = 'connections'
    hard_limit = 10000
    soft_limit = 10000

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
